---
- hosts: all
  vars:
   - docroot: /var/www/dotcom
   - domain: superterran.com
   - email: superterran@gmail.com

  tasks:
   - name: check if epel is on server
     stat: path=~/epel-release-7-7.noarch.rpm
     register: epel

   - name: add repository
     shell: "wget -nc https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-7.noarch.rpm && rpm -ivh epel-release-7-7.noarch.rpm"
     when: epel.stat.exists != True

   - name: install prereqs 
     yum: pkg=git,httpd,ansible state=installed update_cache=true

   - name: copy over httpd vhost
     template: src=vhost.conf dest=/etc/httpd/conf.d/100-{{ domain }}.conf

   - name: ensure latest version of codebase is cloned down with submodules
     git: repo=git@github.com:superterran/dotcom.git
          accept_hostkey=yes
          track_submodules=yes
          dest={{ docroot }}
          force=yes
          update=yes
    
