---
- hosts: all

  tasks:

   - name: restart httpd
     service: name=httpd state=restarted

   - name: open up port 80
     iptables: chain=INPUT protocol=tcp match=tcp destination_port=80 jump=ACCEPT
